### PR TITLE
Province adding

### PR DESCRIPTION
**Pull request by JoMakka**
I think everything is ok

### CODE REVIEW

**Review by Kurash1 — CHANGES_REQUESTED** [review]
Looks mostly alright but 49 is too large, and I think you could do with making the province borders sharper, I usually do this by setting my pencil to 1 px and shaking my mouse while following the border.

So make 49 smaller (maybe split into 2)
And make province borders more jagged.

**Comment by JoMakka** [comment]
why borders should be jagged?

**Comment by Kurash1** [comment]
blobby borders (as they are now) look ugly, your general province positions, and rough shapes are fine. But individual provinces look ugly since their borders are "floaty" making borders more jagged and sharp creates the illusion that they're describing more complex political situations, but also it's just a general style of eu4.

You'd also feel off if you saw a perfectly circular sea tile.

**Review by Kurash1 — APPROVED** [review]
LGTM

**Pull request merged**
